export const assets = {
    foodIcon: require("../assets/icons/testFoodIcon.jpg"),
    food: require("../assets/icons/carrot.png"),
    fridge: require("../assets/icons/fridge.png"),
    hamburger: require("../assets/icons/hamburger.png"),
    trash: require("../assets/icons/trash.png"),
    list: require("../assets/icons/list.png"),
    chevronRight: require("../assets/icons/chevron-right.png"),
    addToListIcon: require("../assets/icons/addToListIcon.png"),
    deleteIcon: require("../assets/icons/deleteIcon.png"),
    homeIcon: require("../assets/icons/homeIcon.png"),
    settingsIcon: require("../assets/icons/settingsIcon.png"),
    searchIcon: require("../assets/icons/searchIcon.png"),
    backgroundMobile: require("../assets/backgrounds/backgroundMobile.jpeg"),
    logoFridge: require("../assets/logos/LogoFridge.png"),
};
